### ISSUE TITLE
No module named 'click'

### ISSUE THREAD

**Issue by BabblingBafoon** [JeffersonQin/dayone2markdown#1]
I am trying to run this on Windows 10. I installed Python from the Microsoft Store. I may be (probably) doing something wrong, but I am not able to get either script to run, even the help message, because I keep getting errors about 'click'.
![image](https://user-images.githubusercontent.com/99982983/162583108-fb015b6e-d546-4ae4-bd88-4fe8e1767c81.png)

I even tried creating a copy of the "py" files and commenting out the 'click' and 'cli' lines, and while it then doesn't throw an error, it also doesn't do anything.

**Comment by JeffersonQin** [comment]
You need to install the `click` module. Try the following command:


```
pip3 install click
```

**Comment by BabblingBafoon** [comment]
I kind of feel like an idiot, but that worked and got me past that error. When I checked the files the only thing it complained about was no folder named 'audios', which is true since I have no audio recordings... just pics and vids.

So I attempted to convert and I immediately get an error: No module named 'dateutil'

I attempted `pip3 install dateutil`, but it errors with "no matching distribution found for dateutil"

Sorry to be a pain.

**Comment by BabblingBafoon** [comment]
I found a command that worked! `pip3 install python-dateutil`

Sorry for my ignorance. After it installed dateutil I ran the conversion and it seems to have worked perfectly!! Thanks so much for sharing this!!

**Comment by JeffersonQin** [comment]
Everyone starts from a newbie. Feel free to ask!

p.s. please close the issue if problems are resolved.

**Comment by JeffersonQin** [comment]
You need to install the `click` module. Try the following command:


```
pip3 install click
```



---Original---
From: ***@***.***&gt;
Date: Sun, Apr 10, 2022 00:39 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [JeffersonQin/dayone2markdown] No module named 'click' (Issue #1)




 
I am trying to run this on Windows 10. I installed Python from the Microsoft Store. I may be (probably) doing something wrong, but I am not able to get either script to run, even the help message, because I keep getting errors about 'click'.
 
 
I even tried creating a copy of the "py" files and commenting out the 'click' and 'cli' lines, and while it then doesn't throw an error, it also doesn't do anything.
